"""Shared constants and configuration."""

HEAVY_DIRS = {
    "node_modules",
    "dist",
    "build",
    "target",
    "__pycache__",
    ".tox",
    ".mypy_cache",
    ".idea",
    ".vscode",
    ".venv",
    "venv",
}

# Icon mapping (Nerd Fonts)
ICONS = {
    "git": "",
    "folder": "",
    "success": "",
    "error": "",
    "info": "",
    "warning": "",
    "exclude": "",
    "commit": "",
    "push": "",
    "pull": "",
    "branch": "",
    "main_branch": "",
    "remote": "",
    "add": "",
    "remove": "",
    "separator": "─",
    "dot": "•",
    "file": "",
    "clock": "",
    "calendar": "",
    "project": "",
    "check": "",
    "rocket": "",
    "sparkles": "󰙨",
    "python": "󰌠",
    "js": "",
    "code": "",
    "html": "",
    "css": "",
    "database": "",
    "config": "",
    "image": "",
    "sound": "",
    "video": "",
    "archive": "",
    "text": "",
    "clone": "",
    "star": "",
    "github": "",
    "fork": "",
    "user": "",
    "globe": "",
    "lock": "",
    "unlock": "",
    "public": "",
    "private": "",
}

# File type to icon mapping
FILE_ICONS = {
    # Programming languages
    "py": "python",
    "ipynb": "python",
    "js": "js",
    "jsx": "js",
    "ts": "js",
    "tsx": "js",
    "html": "html",
    "css": "css",
    "php": "code",
    "java": "code",
    "c": "code",
    "cpp": "code",
    "cs": "code",
    "go": "code",
    "rs": "code",
    "rb": "code",
    "swift": "code",
    "kt": "code",
    "sh": "code",
    # Data files
    "json": "database",
    "yml": "config",
    "yaml": "config",
    "xml": "database",
    "csv": "database",
    "sql": "database",
    # Config files
    "ini": "config",
    "cfg": "config",
    "conf": "config",
    "env": "config",
    "gitignore": "config",
    # Media files
    "jpg": "image",
    "jpeg": "image",
    "png": "image",
    "gif": "image",
    "svg": "image",
    "mp3": "sound",
    "wav": "sound",
    "mp4": "video",
    "mov": "video",
    # Archives
    "zip": "archive",
    "tar": "archive",
    "gz": "archive",
    "rar": "archive",
    # Documents
    "txt": "text",
    "md": "text",
    "pdf": "text",
    "doc": "text",
    "docx": "text",
}
